export default function Head() {
  return (
    <head>
      <title>Create Next App</title>
      <meta
        content='width=device-width, initial-scale=1'
        name='viewport'
      />
      <meta
        name='description'
        content='Generated by create next app'
      />
      <link
        rel='icon'
        href='/favicon.ico'
      />
      <link
        rel='preconnect'
        href='https://fonts.googleapis.com'
      />
      <link
        rel='preconnect'
        href='https://fonts.gstatic.com'
        crossOrigin
      />
      <link
        href='https://fonts.googleapis.com/css2?family=Crimson+Text:ital,wght@0,400;0,600;0,700;1,400;1,600;1,700&display=swap'
        rel='stylesheet'
      />
    </head>
  );
}
